// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXS3MNgdcKdjQ_pzeNGm6fkY96G7O5AQk',
    appId: '1:649773768549:web:4d4cee96c9460fcf99cb8c',
    messagingSenderId: '649773768549',
    projectId: 'advmobprog-firebase-444d6',
    authDomain: 'advmobprog-firebase-444d6.firebaseapp.com',
    storageBucket: 'advmobprog-firebase-444d6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp_NFiipj37nF52LWBxl-ufOyKgE3UgIc',
    appId: '1:649773768549:android:4c13f4cea6afdf2499cb8c',
    messagingSenderId: '649773768549',
    projectId: 'advmobprog-firebase-444d6',
    storageBucket: 'advmobprog-firebase-444d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_9wIJXZC1iq3zMYzdj03E0pX0oqQLS04',
    appId: '1:649773768549:ios:d13ac74120d0685799cb8c',
    messagingSenderId: '649773768549',
    projectId: 'advmobprog-firebase-444d6',
    storageBucket: 'advmobprog-firebase-444d6.firebasestorage.app',
    iosBundleId: 'com.example.labact2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_9wIJXZC1iq3zMYzdj03E0pX0oqQLS04',
    appId: '1:649773768549:ios:d13ac74120d0685799cb8c',
    messagingSenderId: '649773768549',
    projectId: 'advmobprog-firebase-444d6',
    storageBucket: 'advmobprog-firebase-444d6.firebasestorage.app',
    iosBundleId: 'com.example.labact2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXS3MNgdcKdjQ_pzeNGm6fkY96G7O5AQk',
    appId: '1:649773768549:web:0e80e6a703a37f8e99cb8c',
    messagingSenderId: '649773768549',
    projectId: 'advmobprog-firebase-444d6',
    authDomain: 'advmobprog-firebase-444d6.firebaseapp.com',
    storageBucket: 'advmobprog-firebase-444d6.firebasestorage.app',
  );
}
